version: '3.8'

services:
  grafana-test-1:
    user: root
    image: ${GRAFANA_IMAGE:-grafana/grafana:latest}
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0-ubuntu}
        development: ${DEVELOPMENT:-false}
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      # - NODE_ENV=development
      - GF_LOG_FILTERS=plugin.grafana-duckdb-datasource:debug
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=1
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-duckdb-datasource
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-duckdb-datasource
      - ./e2e/provisioning:/etc/grafana/provisioning
      - ./:/root/grafana-duckdb-datasource

  grafana-test-2:
    user: root
    image: ${GRAFANA_IMAGE:-grafana/grafana-enterprise:latest}
    ports:
      - "3002:3000"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0-ubuntu}
        development: ${DEVELOPMENT:-false}
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_LOG_FILTERS=plugin.grafana-duckdb-datasource:debug
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=1
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-duckdb-datasource
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-duckdb-datasource
      - ./e2e/provisioning:/etc/grafana/provisioning
      - ./:/root/grafana-duckdb-datasource
