name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions: read-all

jobs:
  build:
    name: Build, lint and unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm64-s ]
    outputs:
      plugin-id: ${{ steps.metadata.outputs.plugin-id }}
      plugin-version: ${{ steps.metadata.outputs.plugin-version }}
      has-e2e: ${{ steps.check-for-e2e.outputs.has-e2e }}
      has-backend: ${{ steps.check-for-backend.outputs.has-backend }}
    env:
      GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up architecture-specific variables
        id: arch-setup
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            echo "arch=amd64" >> $GITHUB_OUTPUT
            echo "other-arch=amd64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "ubuntu-22.04-arm64-s" ]; then
            echo "arch=aarch64" >> $GITHUB_OUTPUT
            echo "other-arch=arm64" >> $GITHUB_OUTPUT
          fi

      - name: Sysdeps
        env:
          DUCKDB_VERSION: 1.1.3
        run: |
          echo "DUCKDB_VERSION: ${DUCKDB_VERSION}"
          sudo apt update -qq
          sudo apt install -y bash gcc musl-dev
          sudo apt install -y curl libstdc++-12-dev g++ zip 
          curl -v -o duckdb.zip -L "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/duckdb_odbc-linux-${{ steps.arch-setup.outputs.arch }}.zip"
          unzip duckdb.zip 
          sudo mv duckdb_odbc-linux-${{ steps.arch-setup.outputs.arch }}/libduckdb_odbc.so /lib/
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --registry=https://grafana-data-source-npm.fly.dev --legacy-peer-deps

      - name: Check types
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:ci
      - name: Build frontend
        run: npm run build

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        env:
          MAGEFILE_DEBUG: true
          GOOS: linux
          CGO_ENABLED: 1
        run: |
          go install github.com/magefile/mage@${MAGE_VERSION:-latest}
          mage coverage

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        env:
          MAGEFILE_DEBUG: true
          GOOS: linux
          CGO_ENABLED: 1
        run: |
          go install github.com/magefile/mage@${MAGE_VERSION:-latest}
          mage "${{ steps.arch-setup.outputs.arch }}"

      - name: Check for E2E
        id: check-for-e2e
        run: |
          if [ -f "playwright.config.ts" ]
          then
            # TODO: explore e2e more later
            # echo "has-e2e=true" >> $GITHUB_OUTPUT
            echo "has-e2e but not using"
          fi

      - name: Sign plugin
        run: npm run sign
        if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN != '' }}

      - name: Get plugin metadata
        id: metadata
        run: |
          sudo apt-get install jq

          export GRAFANA_PLUGIN_ID=$(cat dist/plugin.json | jq -r .id)
          export GRAFANA_PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)
          export GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.zip

          echo "plugin-id=${GRAFANA_PLUGIN_ID}" >> $GITHUB_OUTPUT
          echo "plugin-version=${GRAFANA_PLUGIN_VERSION}" >> $GITHUB_OUTPUT
          echo "archive=${GRAFANA_PLUGIN_ARTIFACT}" >> $GITHUB_OUTPUT

      - name: Package plugin
        id: package-plugin
        run: |
          mv dist ${{ steps.metadata.outputs.plugin-id }}
          zip -r ${{ steps.metadata.outputs.archive }} ${{ steps.metadata.outputs.plugin-id }}
          sha1sum ${{ steps.metadata.outputs.archive }} > ${{ steps.metadata.outputs.archive }}.sha1

      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.metadata.outputs.plugin-id }}-${{ steps.metadata.outputs.plugin-version }}-${{ steps.arch-setup.outputs.other-arch }}
          path: |
            ${{ steps.metadata.outputs.archive }}
            ${{ steps.metadata.outputs.archive }}.sha1
          retention-days: 7

  resolve-versions:
    name: Resolve e2e images
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: build
    if: ${{ needs.build.outputs.has-e2e == 'true' }}
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@main

  playwright-tests:
    needs: [resolve-versions, build]
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        GRAFANA_IMAGE: ${{fromJson(needs.resolve-versions.outputs.matrix)}}
    name: e2e test ${{ matrix.GRAFANA_IMAGE.name }}@${{ matrix.GRAFANA_IMAGE.VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download plugin
        uses: actions/download-artifact@v4
        with:
          path: dist
          name: ${{ needs.build.outputs.plugin-id }}-${{ needs.build.outputs.plugin-version }}

      - name: Execute permissions on binary
        if: needs.build.outputs.has-backend == 'true'
        run: |
          chmod +x ./dist/gpx_*

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dev dependencies
        run: npm ci

      - name: Start Grafana
        run: |
          docker compose pull
          DEVELOPMENT=false GRAFANA_VERSION=${{ matrix.GRAFANA_IMAGE.VERSION }} GRAFANA_IMAGE=${{ matrix.GRAFANA_IMAGE.NAME }} docker compose up -d

      - name: Wait for Grafana to start
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000/'
          responseCode: 200
          timeout: 60000
          interval: 500

      - name: Install Playwright Browsers
        run: npm exec playwright install chromium --with-deps

      - name: Run Playwright tests
        id: run-tests
        run: npm run e2e

      - name: Docker logs
        if: ${{ always() && steps.run-tests.outcome == 'failure' }}
        run: |
          docker logs grafana-duckdb-datasource >& grafana-server.log

      - name: Stop grafana docker
        run: docker compose down

      - name: Upload server log
        uses: actions/upload-artifact@v4
        if: ${{ always() && steps.run-tests.outcome == 'failure' }}
        with:
          name: ${{ matrix.GRAFANA_IMAGE.NAME }}-v${{ matrix.GRAFANA_IMAGE.VERSION }}-${{github.run_id}}-server-log
          path: grafana-server.log
          retention-days: 5

      # Uncomment this step to upload the Playwright report to Github artifacts.
      # If your repository is public, the report will be public on the Internet so beware not to expose sensitive information.
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   if: ${{ always() && steps.run-tests.outcome == 'failure' }}
      #   with:
      #     name: playwright-report-${{ matrix.GRAFANA_IMAGE.NAME }}-v${{ matrix.GRAFANA_IMAGE.VERSION }}-${{github.run_id}}
      #     path: playwright-report/
      #     retention-days: 5
